import json

corpus = [
    {'sentence': 'I live in a house near the mountains.', 'level': 'A1'},
    {'sentence': 'I have two brothers and one sister, and I was born last.', 'level': 'A1'},
    {'sentence': 'My father teaches mathematics, and my mother is a nurse at a big hospital.', 'level': 'A1'},
    {'sentence': 'My brothers are very smart and work hard in school.', 'level': 'A1'},
    {'sentence': 'My sister is a nervous girl, but she is very kind. ', 'level': 'A1'},
    {'sentence': 'My grandmother also lives with us.', 'level': 'A1'},
    {'sentence': 'She came from Italy when I was two years old.', 'level': 'A1'},
    {'sentence': 'She has grown old, but she is still very strong.', 'level': 'A1'},
    {'sentence': 'She cooks the best food!', 'level': 'A1'},
    {'sentence': 'My family is very important to me.', 'level': 'A1'},
    {'sentence': 'We do lots of things together.', 'level': 'A1'},
    {'sentence': 'My brothers and I like to go on long walks in the mountains.', 'level': 'A1'},
    {'sentence': 'My sister likes to cook with my grandmother.', 'level': 'A1'},
    {'sentence': 'On the weekends we all play board games together.', 'level': 'A1'},
    {'sentence': 'We laugh and always have a good time.', 'level': 'A1'},
    {'sentence': 'I love my family very much.', 'level': 'A1'},
    {'sentence': 'First, I wake up.', 'level': 'A1'},
    {'sentence': 'Then, I get dressed.', 'level': 'A1'},
    {'sentence': 'I walk to school.', 'level': 'A1'},
    {'sentence': 'I do not ride a bike.', 'level': 'A1'},
    {'sentence': 'I do not ride the bus.', 'level': 'A1'},
    {'sentence': 'I like to go to school.', 'level': 'A1'},
    {'sentence': 'It rains.', 'level': 'A1'},
    {'sentence': 'I do not like rain.', 'level':'A1'},
    {'sentence': 'I eat lunch.', 'level': 'A1'},
    {'sentence': 'I eat a sandwich and an apple.', 'level': 'A1'},
    {'sentence': 'I play outside.', 'level': 'A1'},
    {'sentence': 'I like to play.', 'level': 'A1'},
    {'sentence': 'I read a book.', 'level': 'A1'},
    {'sentence': 'I like to read books.', 'level': 'A1'},
    {'sentence': 'I walk home.', 'level': 'A1'},
    {'sentence': 'I do not like walking home.', 'level': 'A1'},
    {'sentence': 'My mother cooks soup for dinner.', 'level': 'A1'},
    {'sentence': 'The soup is hot.', 'level': 'A1'},
    {'sentence': 'Then, I go to bed.', 'level': 'A1'},
    {'sentence': 'I do not like to go to bed.', 'level': 'A1'},
    {'sentence': 'Nice to meet you!', 'level': 'A1'},
    {'sentence': 'My name is John Smith.', 'level': 'A1'},
    {'sentence': 'I am 19 and a student in college.', 'level': 'A1'},
    {'sentence': 'I go to college in New York.', 'level': 'A1'},
    {'sentence': 'My favorite courses are Geometry, French, and History.', 'level': 'A1'},
    {'sentence': 'English is my hardest course.', 'level': 'A1'},
    {'sentence': 'My professors are very friendly and smart.', 'level': 'A1'},
    {'sentence': 'It’s my second year in college now.', 'level': 'A1'},
    {'sentence': 'I love it!', 'level': 'A1'},
    {'sentence': 'I live in a big house on Ivy Street.', 'level': 'A1'},
    {'sentence': 'It’s near the college campus.', 'level': 'A1'},
    {'sentence': 'I share the house with three other students.', 'level': 'A1'},
    {'sentence': 'Their names are Bill, Tony, and Paul.', 'level': 'A1'},
    {'sentence': 'We help each other with homework.', 'level': 'A1'},
    {'sentence': 'On the weekend, we play football together.', 'level': 'A1'},
    {'sentence': 'I have a younger brother.', 'level': 'A1'},
    {'sentence': 'He just started high school.', 'level': 'A1'},
    {'sentence': 'He is 14 and lives with my parents.', 'level': 'A1'},
    {'sentence': 'They live on Mulberry Street in Boston.', 'level': 'A1'},
    {'sentence': 'Sometimes they visit me in New York.', 'level': 'A1'},
    {'sentence': 'I am happy when they visit.', 'level': 'A1'},
    {'sentence': 'My Mom always brings me sweets and candy when they come.', 'level': 'A1'},
    {'sentence': 'I really miss them, too!', 'level': 'A1'},
    {'sentence': 'Every year we go to Florida.', 'level': 'A1'},
    {'sentence': 'We like to go to the beach.', 'level': 'A1'},
    {'sentence': 'My favorite beach is called Emerson Beach.', 'level': 'A1'},
    {'sentence': 'It is very long, with soft sand and palm trees.', 'level': 'A1'},
    {'sentence': 'It is very beautiful.', 'level': 'A1'},
    {'sentence': 'I like to make sandcastles and watch the sailboats go by.', 'level': 'A1'},
    {'sentence': 'Sometimes there are dolphins and whales in the water!', 'level': 'A1'},
    {'sentence': 'Every morning we look for shells in the sand.', 'level': 'A1'},
    {'sentence': 'I found fifteen big shells last year.', 'level': 'A1'},
    {'sentence': 'I put them in a special place in my room.', 'level': 'A1'},
    {'sentence': 'This year I want to learn to surf.', 'level': 'A1'},
    {'sentence': 'It is hard to surf, but so much fun!', 'level': 'A1'},
    {'sentence': 'My sister is a good surfer.', 'level': 'A1'},
    {'sentence': 'She says that she can teach me.', 'level': 'A1'},
    {'sentence': 'I hope I can do it!', 'level': 'A1'},
    {'sentence': 'Jack was hungry.', 'level': 'A1'},
    {'sentence': 'He walked to the kitchen.', 'level': 'A1'},
    {'sentence': 'He got out some eggs.', 'level': 'A1'},
    {'sentence': 'He took out some oil.', 'level': 'A1'},
    {'sentence': 'He placed a skillet on the stove.', 'level': 'A1'},
    {'sentence': 'Next, he turned on the heat.', 'level': 'A1'},
    {'sentence': 'He poured the oil into the skillet.', 'level': 'A1'},
    {'sentence': 'He cracked the eggs into a bowl.', 'level': 'A1'},
    {'sentence': 'He stirred the eggs.', 'level': 'A1'},
    {'sentence': 'Then, he poured them into the hot skillet.', 'level': 'A1'},
    {'sentence': 'He waited while the eggs cooked.', 'level': 'A1'},
    {'sentence': 'They cooked for two minutes.', 'level': 'A1'},
    {'sentence': 'He heard them cooking.', 'level': 'A1'},
    {'sentence': 'They popped in the oil.', 'level': 'A1'},
    {'sentence': 'Next, Jack put the eggs on a plate.', 'level': 'A1'},
    {'sentence': 'He placed the plate on the dining room table.', 'level': 'A1'},
    {'sentence': 'Jack loved looking at his eggs.', 'level': 'A1'},
    {'sentence': 'They looked pretty on the white plate.', 'level': 'A1'},
    {'sentence': 'He sat down in the large wooden chair.', 'level': 'A1'},
    {'sentence': 'He thought about the day ahead.', 'level': 'A1'},
    {'sentence': 'He ate the eggs with a spoon.', 'level': 'A1'},
    {'sentence': 'They were good.', 'level': 'A1'},
    {'sentence': 'He washed the plate with dishwashing soap.', 'level': 'A1'},
    {'sentence': 'Then, he washed the pan.', 'level': 'A1'},
    {'sentence': 'He got a sponge damp.', 'level': 'A1'},
    {'sentence': 'Finally, he wiped down the table.', 'level': 'A1'},
    {'sentence': 'Next, Jack watched TV.', 'level': 'A1'},
    {'sentence': 'Mr. and Mrs. Smith have one son and one daughter.', 'level': 'A1'},
    {'sentence': 'The son’s name is John.', 'level': 'A1'},
    {'sentence': 'The daughter’s name is Sarah.', 'level': 'A1'},
    {'sentence': 'The Smiths live in a house.', 'level': 'A1'},
    {'sentence': 'They have a living room.', 'level': 'A1'},
    {'sentence': 'They watch TV in the living room.', 'level': 'A1'},
    {'sentence': 'The father cooks food in the kitchen.', 'level': 'A1'},
    {'sentence': 'They eat in the dining room.', 'level': 'A1'},
    {'sentence': 'The house has two bedrooms.', 'level': 'A1'},
    {'sentence': 'They sleep in the bedrooms.', 'level': 'A1'},
    {'sentence': 'They keep their clothes in the closet.', 'level': 'A1'},
    {'sentence': 'There is one bathroom.', 'level': 'A1'},
    {'sentence': 'They brush their teeth in the bathroom.', 'level': 'A1'},
    {'sentence': 'The house has a garden.', 'level': 'A1'},
    {'sentence': 'John and Sarah play in the garden.', 'level': 'A1'},
    {'sentence': 'They have a dog.', 'level': 'A1'},
    {'sentence': 'John and Sarah like to play with the dog.', 'level': 'A1'},
    {'sentence': 'I just returned from the greatest summer vacation!', 'level': 'A2'},
    {'sentence': 'It was so fantastic, I never wanted it to end.', 'level': 'A2'},
    {'sentence': 'I spent eight days in Paris, France.', 'level': 'A2'},
    {'sentence': 'My best friends, Henry and Steve, went with me.', 'level': 'A2'},
    {'sentence': 'We had a beautiful hotel room in the Latin Quarter, and it wasn’t even expensive.', 'level': 'A2'},
    {'sentence': 'We had a balcony with a wonderful view.', 'level': 'A2'},
    {'sentence': 'We visited many famous tourist places.', 'level': 'A2'},
    {'sentence': 'My favorite was the Louvre, a well-known museum.', 'level': 'A2'},
    {'sentence': 'I was always interested in art, so that was a special treat for me.', 'level': 'A2'},
    {'sentence': 'The museum is so huge, you could spend weeks there.', 'level': 'A2'},
    {'sentence': 'Henry got tired walking around the museum and said “Enough! I need to take a break and rest.”', 'level': 'A2'},
    {'sentence': 'We took lots of breaks and sat in cafes along the river Seine.', 'level': 'A2'},
    {'sentence': 'The French food we ate was delicious.', 'level': 'A2'},
    {'sentence': 'The wines were tasty, too.', 'level': 'A2'},
    {'sentence': 'Steve’s favorite part of the vacation was the hotel breakfast.', 'level': 'A2'},
    {'sentence': 'He said he would be happy if he could eat croissants like those forever.', 'level': 'A2'},
    {'sentence': 'We had so much fun that we’re already talking about our next vacation!', 'level': 'A2'},
    {'sentence': 'Lucas goes to school every day of the week.', 'level': 'A2'},
    {'sentence': 'He has many subjects to go to each school day: English, art, science, mathematics, gym, and history.', 'level': 'A2'},
    {'sentence': 'His mother packs a big backpack full of books and lunch for Lucas.', 'level': 'A2'},
    {'sentence': 'His first class is English, and he likes that teacher very much.', 'level': 'A2'},
    {'sentence': 'His English teacher says that he is a good pupil, which Lucas knows means that she thinks he is a good student.', 'level': 'A2'},
    {'sentence': 'His next class is art.', 'level': 'A2'},
    {'sentence': 'He draws on paper with crayons and pencils and sometimes uses a ruler.', 'level': 'A2'},
    {'sentence': 'Lucas likes art.', 'level': 'A2'},
    {'sentence': 'It is his favorite class.', 'level': 'A2'},
    {'sentence': 'His third class is science.', 'level': 'A2'},
    {'sentence': 'This class is very hard for Lucas to figure out, but he gets to work with his classmates a lot, which he likes to do.', 'level': 'A2'},
    {'sentence': 'His friend, Kyle, works with Lucas in science class, and they have fun.', 'level': 'A2'},
    {'sentence': 'Then Lucas gets his break for lunch.', 'level': 'A2'},
    {'sentence': 'He sits with Kyle while he eats.', 'level': 'A2'},
    {'sentence': 'The principal, or the headmaster as some call him, likes to walk around and talk to students during lunch to check that they are all behaving.', 'level': 'A2'},
    {'sentence': 'The next class is mathematics, which most of the students just call math.', 'level': 'A2'},
    {'sentence': 'Kyle has trouble getting a good grade in mathematics, but the teacher is very nice and helpful.', 'level': 'A2'},
    {'sentence': 'His fourth class is gym.', 'level': 'A2'},
    {'sentence': 'It is just exercising.', 'level': 'A2'},
    {'sentence': 'History is his last class of the day.', 'level': 'A2'},
    {'sentence': 'Lucas has a hard time staying awake.', 'level': 'A2'},
    {'sentence': 'Many lessons are boring, and he is very tired after doing gym.', 'level': 'A2'},
    {'sentence': 'There are seven days of the week, or uniquely named 24-hour periods designed to provide scheduling context and make time more easily measureable.', 'level': 'A2'},
    {'sentence': 'Each of these days is identifiable by specific plans, moods, and tones.', 'level': 'A2'},
    {'sentence': 'Monday is viewed by many to be the "worst" day of the week, as it marks the return to work following the weekend, when most full-time employees are given two days off.', 'level': 'A2'},
    {'sentence': 'Most students attend school in the morning and return home in the afternoon (usually from about eight until three or seven until two).', 'level': 'A2'},
    {'sentence': 'Most workers go to work in the morning and return home in the evening (usually from nine to five or eight to four).', 'level': 'A2'},
    {'sentence': 'Tuesday is the second day of the week, and is in many ways similar to Monday.', 'level': 'A2'},
    {'sentence': 'Not a whole lot of changes, schedule-wise, between Tuesday and Monday.', 'level': 'A2'},
    {'sentence': 'Most individuals go to school or work and return home to watch television, play video games, make plans with friends, spend time with family, read, or engage in a similar leisure-related activity.', 'level': 'A2'},
    {'sentence': 'Wednesday is the third day of the week, and serves as the "middle" of the work week.', 'level': 'A2'},
    {'sentence': 'Some individuals refer to Wednesday as "hump day," as once its workday is complete, employees will have passed the work-week "hump," and will be on the downturn, as only two days on the job will remain in the week.', 'level': 'A2'},
    {'sentence': 'Thursday is the fourth day of the week, and is viewed favorably by many, as it’s rather close to the end of the work week.', 'level': 'A2'},
    {'sentence': 'Friday is the fifth day of the week, and marks the end of the workweek and school-week for the vast majority of employees and students.', 'level': 'A2'},
    {'sentence': 'By Friday afternoon/evening, most students/workers cannot wait to leave and go home, as they won’t have to report back to school/work until Monday.', 'level': 'A2'},
    {'sentence': 'Saturday is perhaps the most highly regarded day of the week. ', 'level': 'A2'},
    {'sentence': 'Because Sunday follows it (and there is presumably no work or school to attend, for most individuals), everyone is free to stay out (or awake) until late at night, having fun with plans or other leisure-related activities.', 'level': 'A2'},
    {'sentence': 'To be sure, Saturday is generally thought of as a day to partake in hobbies that couldn’t otherwise be enjoyed during the regular week.', 'level': 'A2'},
    {'sentence': 'Sunday is the final day of the week, and is used by most as a day of rest.', 'level': 'A2'},
    {'sentence': 'Fewer late-night plans are made on Sundays, compared to Saturdays, as most individuals have to wake up for work or school on Monday morning.', 'level': 'A2'},
    {'sentence': 'Good morning, Cecilia, how are you feeling today?', 'level': 'A2'},
    {'sentence': 'I do not feel very well, Doctor Klein.', 'level': 'A2'},
    {'sentence': 'I hope that you can treat my illness.', 'level': 'A2'},
    {'sentence': 'I’m sorry that you feel very sick.', 'level': 'A2'},
    {'sentence': 'Tell me some of your symptoms so that I can give you a proper diagnosis.', 'level': 'A2'},
    {'sentence': 'I have not felt well since yesterday afternoon.', 'level': 'A2'},
    {'sentence': 'The symptoms began with a headache and a gradual sore throat.', 'level': 'A2'},
    {'sentence': 'I drank tea with lemon and honey, and I went to bed early.', 'level': 'A2'},
    {'sentence': 'However, I am extremely exhausted, and I don’t feel any better today.', 'level': 'A2'},
    {'sentence': 'I have seen these symptoms recently in some of my other patients.', 'level': 'A2'},
    {'sentence': 'I’ll check your temperature and examine your throat in order to give you a proper diagnosis.', 'level': 'A2'},
    {'sentence': 'Thank you, Doctor.', 'level': 'A2'},
    {'sentence': 'I can already see that your throat is very red.', 'level': 'A2'},
    {'sentence': 'Your temperature of 100 degrees indicates that you are running a mild fever.', 'level': 'A2'},
    {'sentence': 'I am afraid that you might have the flu.', 'level': 'A2'},
    {'sentence': 'What is the best way to cure my symptoms?', 'level': 'A2'},
    {'sentence': 'You will need plenty of rest, and you should drink fluids frequently in order to stay hydrated.', 'level': 'A2'},
    {'sentence': 'You’ve also just started to show symptoms, so I can prescribe you a medication that can reduce fever and shorten the duration of your illness.', 'level': 'A2'},
    {'sentence': 'Should I stay home from work as well?', 'level': 'A2'},
    {'sentence': 'Yes, you should remain in bed until the fever breaks. ', 'level': 'A2'},
    {'sentence': 'You should also wait until 24 hours after the fever has broken before you return to work', 'level': 'A2'},
    {'sentence': 'You do not want to risk getting your coworkers sick as well.', 'level': 'A2'},
    {'sentence': 'I suppose I will just take it easy and relax for a couple of days.', 'level': 'A2'},
    {'sentence': 'Thank you, doctor, for all of your help!', 'level': 'A2'},
    {'sentence': 'No problem!', 'level': 'A2'},
    {'sentence': 'Try your best to rest for a couple of days.', 'level': 'A2'},
    {'sentence': 'I hope you feel better soon!', 'level': 'A2'},
    {'sentence': 'Sandra and Paul are at a steak restaurant.', 'level': 'A2'},
    {'sentence': 'A waiter greets them.', 'level': 'A2'},
    {'sentence': 'Do you know what you would like to drink?', 'level': 'A2'},
    {'sentence': 'Water and orange juice.', 'level': 'A2'},
    {'sentence': 'Here are your menus.', 'level': 'A2'},
    {'sentence': 'The waiter brings water for Paul and orange juice for Sandra.', 'level': 'A2'},
    {'sentence': 'What would you like to order?', 'level': 'A2'},
    {'sentence': 'I would like a 12-ounce steak and mashed potatoes.', 'level': 'A2'},
    {'sentence': 'The same thing, but with green beans', 'level': 'A2'},
    {'sentence': 'And two orders of garlic bread.', 'level': 'A2'},
    {'sentence': 'You should have it in soon.', 'level': 'A2'},
    {'sentence': 'The waiter returns after an hour.', 'level': 'A2'},
    {'sentence': 'Sorry for your wait.', 'level': 'A2'},
    {'sentence': 'Here are two orders of 12-ounce steaks with mashed potatoes and garlic bread.', 'level': 'A2'},
    {'sentence': 'I asked for green beans with mine.', 'level': 'A2'},
    {'sentence': 'I’m sorry, I’ll get those for you.', 'level': 'A2'},
    {'sentence': 'The waiter quickly returns with Sandra’s green beans.', 'level': 'A2'},
    {'sentence': 'Martha is at the grocery store, getting ready for a house party.', 'level': 'A2'},
    {'sentence': 'She has a list of what she needs with her as she goes along.', 'level': 'A2'},
    {'sentence': 'The first section she comes has produce.', 'level': 'A2'},
    {'sentence': 'Martha sees apples, bananas, cherries, grapes, and strawberries.', 'level': 'A2'},
    {'sentence': 'Martha gets her items and looks the bananas.', 'level': 'A2'},
    {'sentence': 'They are on sale for much cheaper than they are normally.', 'level': 'A2'},
    {'sentence': 'She picks 3 bananas.', 'level': 'A2'},
    {'sentence': 'Next are vegetables.', 'level': 'A2'},
    {'sentence': 'She sees potatoes, carrots, tomatoes, onions, mushrooms, and salad in bags.', 'level': 'A2'},
    {'sentence': 'As she is putting her items into her cart, Martha checks the many bags of salad and chooses 2 of them.', 'level': 'A2'},
    {'sentence': 'She pushes her cart ahead.', 'level': 'A2'},
    {'sentence': 'The next section is meat and dairy.', 'level': 'A2'},
    {'sentence': 'She sees meat, fish, cheese, eggs, and milk.', 'level': 'A2'},
    {'sentence': 'She looks at the meat that is on sale and chooses a 5-pound roll of hamburger.', 'level': 'A2'},
    {'sentence': 'She gets the rest of the items in that section.', 'level': 'A2'},
    {'sentence': 'She still needs rice, bread, salt, sugar, and flour.', 'level': 'A2'},
    {'sentence': 'Martha then realizes that she has forgotten something.', 'level': 'A2'},
    {'sentence': 'She runs back and gets 1 container of salt and then rushes to the checkout. ', 'level': 'A2'},
    {'sentence': 'She puts her groceries into her car and leaves.', 'level': 'A2'},
    {'sentence': 'It’s been a while since we have been in touch.', 'level': 'A2'},
    {'sentence': 'How has your semester been?', 'level': 'A2'},
    {'sentence': 'I wanted to send an email update to you let you know how things have been going during my semester abroad here in Malaga, Spain.', 'level': 'A2'},
    {'sentence': 'I’ve already been here for six weeks, and I feel like I am finally adapting to the culture.', 'level': 'A2'},
    {'sentence': 'I’m also speaking the language more fluently.', 'level': 'A2'},
    {'sentence': 'I arrived during the first week of September.', 'level': 'A2'},
    {'sentence': 'The weather has been very nice.', 'level': 'A2'},
    {'sentence': 'Even though it’s October, it’s still rather sunny and warm. ', 'level': 'A2'},
    {'sentence': 'In fact, I went to the beach and swam in the Mediterranean Sea earlier today.', 'level': 'A2'},
    {'sentence': 'I am living with a very welcoming host family.', 'level': 'A2'},
    {'sentence': 'I have my own private bedroom, but we eat breakfast, lunch, and dinner together.', 'level': 'A2'},
    {'sentence': 'On Sundays, we eat a big home-cooked paella for lunch.', 'level': 'A2'},
    {'sentence': 'In Spain, lunch is usually the biggest meal of the day.', 'level': 'A2'},
    {'sentence': 'It’s also very common for the people to take a midday nap right after a big meal.', 'level': 'A2'},
    {'sentence': 'I am actually just waking up from my nap right now!', 'level': 'A2'},
    {'sentence': 'On weekdays, I take classes at the local university.', 'level': 'A2'},
    {'sentence': 'There, I met several native Spanish speakers.', 'level': 'A2'},
    {'sentence': 'They have been very kind and patient with me.', 'level': 'A2'},
    {'sentence': 'At first, I struggled to comprehend their Spanish, but now I understand most of our conversations.', 'level': 'A2'},
    {'sentence': 'They have commented that my Spanish has improved a lot since we first met.', 'level': 'A2'},
    {'sentence': 'Now, I am more confident to use the language in other places like stores and restaurants.', 'level': 'A2'},
    {'sentence': 'I am so glad that I decided to spend the semester here in Spain.', 'level': 'A2'},
    {'sentence': 'We have an extended weekend coming up, so a group of my friends and I are going to travel to France for four days.', 'level': 'A2'},
    {'sentence': 'It’s so easy and inexpensive to travel internationally in Europe.', 'level': 'A2'},
    {'sentence': 'I love it!', 'level': 'A2'},
    {'sentence': 'I look forward to hearing from you soon.', 'level': 'A2'},
    {'sentence': 'Like I said, don’t hesitate to stay in touch more often.', 'level': 'A2'},
    {'sentence': 'Perhaps you could even come to visit!', 'level': 'A2'},
    {'sentence': 'What do you think?', 'level': 'A2'},
    {'sentence': 'My family lives in a small house.', 'level': 'A2'},
    {'sentence': 'It’s simple but pretty.', 'level': 'A2'},
    {'sentence': 'It has a large garden.', 'level': 'A2'},
    {'sentence': 'I like to work in the garden but my sister hates to work in the garden.', 'level': 'A2'},
    {'sentence': 'She prefers to read.', 'level': 'A2'},
    {'sentence': 'She reads in the morning, in the afternoon and at night.', 'level': 'A2'},
    {'sentence': 'I give all of the vegetables to mom and dad.', 'level': 'A2'},
    {'sentence': 'They like to cook in our small kitchen.', 'level': 'A2'},
    {'sentence': 'I eat any vegetable but my sister eats only a few.', 'level': 'A2'},
    {'sentence': 'My family always eats breakfast and dinner together.', 'level': 'A2'},
    {'sentence': 'Then my sister washes the dishes.', 'level': 'A2'},
    {'sentence': 'At night dad likes to listen to music.', 'level': 'A2'},
    {'sentence': 'Mom works on the computer.', 'level': 'A2'},
    {'sentence': 'I watch television and my sister reads.', 'level': 'A2'},
    {'sentence': 'Soon we go to bed.', 'level': 'A2'},
    {'sentence': 'My parents go to bed late but my sister and I go to bed early.', 'level': 'A2'},
    {'sentence': 'I’m ready to go to sleep but my sister wants to keep reading.', 'level': 'A2'},
    {'sentence': 'My name is Bob.', 'level': 'A2'},
    {'sentence': 'Each day I drive my kids to school.', 'level': 'A2'},
    {'sentence': 'My daughter goes to a school that’s far from our house.', 'level': 'A2'},
    {'sentence': 'It takes 30 minutes to get there.', 'level': 'A2'},
    {'sentence': 'Then I drive my son to his school.', 'level': 'A2'},
    {'sentence': 'It’s close to my job.', 'level': 'A2'},
    {'sentence': 'My daughter is in the sixth grade and my son is in the second.', 'level': 'A2'},
    {'sentence': 'They are both good students.', 'level': 'A2'},
    {'sentence': 'My daughter usually sings her favorite songs while I drive.', 'level': 'A2'},
    {'sentence': 'My son usually sleeps.', 'level': 'A2'},
    {'sentence': 'I arrive at the office at 8:30 AM.', 'level': 'A2'},
    {'sentence': 'I say good morning to all my workmates then I get a big cup of hot coffee.', 'level': 'A2'},
    {'sentence': 'I turn on my computer and read my email.', 'level': 'A2'},
    {'sentence': 'Some days I have a lot to read.', 'level': 'A2'},
    {'sentence': 'Soon I need another cup of coffee.', 'level': 'A2'},
    {'sentence': 'Most individuals don’t think about numbers, or numerical representations of quantity, but they play a major part in everyday life.', 'level': 'A2'},
    {'sentence': 'To be sure, numbers determine the time individuals will wake up in the morning, how much money employees earn per hour, what day of the year it is, and much, much more.', 'level': 'A2'},
    {'sentence': 'Additionally, numbers impact everyday living on a much smaller scale.', 'level': 'A2'},
    {'sentence': 'In the grocery store, for instance, numbers determine products’ prices, the amount of a product available for purchase, how much money will need to be paid for products, and a whole lot else.', 'level': 'A2'},
    {'sentence': 'To understand larger numbers, interested persons first need to understand basic numbers, or numbers from one to ten, as they comprise each and every advanced number, or a multi-digit number that indicates a larger amount/quantity.', 'level': 'A2'},
    {'sentence': 'The basic numbers are as follows:', 'level': 'A2'},
    {'sentence': 'He purchased one watermelon from the grocery store.', 'level': 'A2'},
    {'sentence': 'She bought two types of bread from the store.', 'level': 'A2'},
    {'sentence': 'He decided to get three bags of onions when he went shopping.', 'level': 'A2'},
    {'sentence': 'In preparation for the party, Janice bought four cartons of ice cream at the store.', 'level': 'A2'},
    {'sentence': 'Joe picked up five boxes of cereal from the breakfast aisle.', 'level': 'A2'},
    {'sentence': 'A pound of beef costs a lot of money at my favorite grocery store.', 'level': 'A2'},
    {'sentence': 'Seven of the 10 aisles at my local grocery store contain pasta.', 'level': 'A2'},
    {'sentence': 'I bought eight cookies for the price of four at the store.', 'level': 'A2'},
    {'sentence': 'There were only nine loafs of bread left at the grocery store.', 'level': 'A2'},
    {'sentence': 'Ten pineapples sure is a lot, don’t you think?', 'level': 'A2'},
    {'sentence': 'After ten, eleven (11), twelve (12), thirteen (13), fourteen (14), fifteen (15), sixteen (16), seventeen (17), eighteen (18), nineteen (19), and twenty (20) follow.', 'level': 'A2'},
    {'sentence': 'These numbers are seen less in grocery stores, as most prices are 10 dollars or less.', 'level': 'A2'},
    {'sentence': 'It is however worth knowing these numbers, generally and, in terms of grocery shopping, for when the bill must be paid.', 'level': 'A2'},
    {'sentence': 'After twenty, numbers such as twenty-five (25), fifty (50), seventy-five (75), and one hundred (100) follow.', 'level': 'A2'},
    {'sentence': 'So long as one knows the core number, or the number situated in the tens or hundreds position that determines the general amount, understanding these more complicated numbers won’t be difficult.', 'level': 'A2'},
    {'sentence': 'For example thirty-three (33) is simply "thirty" plus three; sixty-seven is "sixty" plus seven; and sixty-nine is simply "sixty" plus nine.', 'level': 'A2'},
    {'sentence': 'My name is Clark, and I will tell you about my city.', 'level': 'A2'},
    {'sentence': 'I live in an apartment.', 'level': 'A2'},
    {'sentence': 'In my city, there is a post office where people mail letters.', 'level': 'A2'},
    {'sentence': 'On Monday, I go to work.', 'level': 'A2'},
    {'sentence': 'I work at the post office.', 'level': 'A2'},
    {'sentence': 'Everyone shops for food at the grocery store.', 'level': 'A2'},
    {'sentence': 'They also eat at the restaurant.', 'level': 'A2'},
    {'sentence': 'The restaurant serves pizza and ice cream.', 'level': 'A2'},
    {'sentence': 'My friends and I go to the park.', 'level': 'A2'},
    {'sentence': 'We like to play soccer at the park.', 'level': 'A2'},
    {'sentence': 'On Fridays, we go to the cinema to see a movie.', 'level': 'A2'},
    {'sentence': 'Children don’t go to school on the weekend.', 'level': 'A2'},
    {'sentence': 'Each day, people go to the hospital when they are sick.', 'level': 'A2'},
    {'sentence': 'The doctors and nurses take care of them.', 'level': 'A2'},
    {'sentence': 'The police keep everyone safe.', 'level': 'A2'},
    {'sentence': 'I am happy to live in my city.', 'level': 'A2'},
    {'sentence': 'George is at the pet store, looking at what kind of pet he might want to get for his birthday.', 'level': 'A2'},
    {'sentence': 'George asked if he could have a horse, but his parents said no because horses are too big.', 'level': 'A2'},
    {'sentence': 'First, he sees dogs and cats.', 'level': 'A2'},
    {'sentence': 'Baby dogs are called puppies.', 'level': 'A2'},
    {'sentence': 'Baby cats are called kittens', 'level': 'A2'},
    {'sentence': 'George likes them because they are easy to take care of and can play a lot, but they will get bigger.', 'level': 'A2'},
    {'sentence': 'George wants a small pet.', 'level': 'A2'},
    {'sentence': 'Then George sees animals that have to live in a cage.', 'level': 'A2'},
    {'sentence': 'He sees rabbits, guinea pigs, and mice.', 'level': 'A2'},
    {'sentence': 'Mice are what you call more than one mouse.', 'level': 'A2'},
    {'sentence': 'He likes these animals because they are small.', 'level': 'A2'},
    {'sentence': 'Birds live in cages too. ', 'level': 'A2'},
    {'sentence': 'George sees a parrot and a canary.', 'level': 'A2'},
    {'sentence': 'He likes them all, but he doesn’t want to clean the cage.', 'level': 'A2'},
    {'sentence': 'George sees the animals in tanks.', 'level': 'A2'},
    {'sentence': 'The tanks full of water have fish and turtles in them.', 'level': 'A2'},
    {'sentence': 'He thinks about a goldfish but decides he likes the turtles more.', 'level': 'A2'},
    {'sentence': 'There are also tanks with rocks and sand that have snakes, spiders, and scorpions, but George is afraid of them.', 'level': 'A2'},
    {'sentence': 'George likes the turtles best, but they won’t fit in the little fishbowls.', 'level': 'A2'},
    {'sentence': 'Turtles need bigger tanks, so they can swim sometimes and hide sometimes.', 'level': 'A2'},
    {'sentence': 'George decides he wants to get a turtle for his birthday.', 'level': 'A2'},
    {'sentence': 'He buys a book on how to take care of a turtle and a list of what types of turtles the store has.', 'level': 'A2'},
    {'sentence': 'Keith recently came back from a trip to Chicago, Illinois.', 'level': 'B1'},
    {'sentence': 'This midwestern metropolis is found along the shore of Lake Michigan. ', 'level': 'B1'},
    {'sentence': 'During his visit, Keith spent a lot of time exploring the city to visit important landmarks and monuments.', 'level': 'B1'},
    {'sentence': 'Keith loves baseball, and he made sure to take a visit to Wrigley Field. ', 'level': 'B1'},
    {'sentence': 'Not only did he take a tour of this spectacular stadium, but he also got to watch a Chicago Cubs game.', 'level': 'B1'},
    {'sentence': 'In the stadium, Keith and the other fans cheered for the Cubs.', 'level': 'B1'},
    {'sentence': 'Keith was happy that the Cubs won with a score of 5-4.', 'level': 'B1'},
    {'sentence': 'Chicago has many historic places to visit.', 'level': 'B1'},
    {'sentence': 'Keith found the Chicago Water Tower impressive as it is one of the few remaining landmarks to have survived the Great Chicago Fire of 1871.', 'level': 'B1'},
    {'sentence': 'Keith also took a walk through Jackson Park, a great outdoor space that hosted the World’s Fair of 1892.', 'level': 'B1'},
    {'sentence': 'The park is great for a leisurely stroll, and it still features some of the original architecture and replicas of monuments that were featured in the World’s Fair.', 'level': 'B1'},
    {'sentence': 'During the last part of his visit, Keith managed to climb the stairs inside of the Willis Tower, a 110-story skyscraper.', 'level': 'B1'},
    {'sentence': 'Despite the challenge of climbing the many flights of stairs, Keith felt that reaching the top was worth the effort.', 'level': 'B1'},
    {'sentence': 'From the rooftop, Keith received a gorgeous view of the city’s skyline with Lake Michigan in the background.', 'level': 'B1'},
    {'sentence': 'A Christian holiday signifying the birth of Jesus, Christmas is widely celebrated and enjoyed across the United States and the world.', 'level': 'B1'},
    {'sentence': 'The holiday always falls on 25 December (regardless of the day of the week), and is typically accompanied by decorations, presents, and special meals.', 'level': 'B1'},
    {'sentence': 'Specifically, the legend behind Christmas is that Santa Claus, a bearded, hefty, jolly, and red-jacket-wearing old man who lives in the North Pole, spends the year crafting presents with his elves, or small, festive, excited Santa-assistants.', 'level': 'B1'},
    {'sentence': 'All the children who behave throughout the year are admitted to the Good List, and will presumably receive their desired gifts on Christmas.', 'level': 'B1'},
    {'sentence': 'Those who don’t behave are placed on the Naughty List, and will presumably (although the matter is determined by parents) receive a lump of coal.', 'level': 'B1'},
    {'sentence': 'Santa Claus is said to fly around the Christmas sky in a sled powered by his magical reindeer, or cold-resistant, mythically powered, individually named animals, delivering presents to each child’s house in the process.', 'level': 'B1'},
    {'sentence': 'Santa is also expected to slide through chimneys to deliver these presents.', 'level': 'B1'},
    {'sentence': 'Homes not equipped with chimneys might "leave the front door cracked open"', 'level': 'B1'},
    {'sentence': 'Children sometimes arrange cookies or other treats on a plate for him to enjoy', 'level': 'B1'},
    {'sentence': 'Gifts are placed underneath a Christmas tree, or a pine tree that’s decorated with ornaments and/or lights and is symbolic of the holiday.', 'level': 'B1'},
    {'sentence': 'Additionally, smaller gifts may be placed inside a stocking, or a sock-shaped, holiday-specific piece of fabric that’s generally hung on the mantle of a fireplace.', 'level': 'B1'},
    {'sentence': 'Homes without fireplaces might use the wall.', 'level': 'B1'},
    {'sentence': 'A Christmas tree’s ornaments, or hanging, typically spherical decorations, in addition to the mentioned lights, may be accompanied by a star.', 'level': 'B1'},
    {'sentence': 'A representation of the Star of Jerusalem that the Three Apostles followed while bringing Baby Jesus gifts and honoring him, in the Bible', 'level': 'B1'},
    {'sentence': 'While eating at a restaurant is an enjoyable and convenient occasional treat, most individuals and families prepare their meals at home.', 'level': 'B1'},
    {'sentence': 'To make breakfast, lunch, and dinner daily, these persons must have the required foods and ingredients on hand and ready to go.', 'level': 'B1'},
    {'sentence': 'foods and ingredients are typically purchased from a grocery store, or an establishment that distributes foods, drinks, household products, and other items that’re used by the typical consumer.', 'level': 'B1'},
    {'sentence': 'Produce, or the term used to describe fresh fruits and vegetables, is commonly purchased by grocery store shoppers.', 'level': 'B1'},
    {'sentence': 'In terms of fruit, most grocery stores offer bananas, apples, oranges, blackberries, raspberries, grapes, pineapples, cantaloupes, watermelons, and more.', 'level': 'B1'},
    {'sentence': 'Other grocery stores with larger produce selections might offer the listed fruits in addition to less common fruits, including mangoes, honeydews, starfruits, coconuts, and more.', 'level': 'B1'},
    {'sentence': 'Depending on the grocery store, customers can purchase fruits in a few different ways.', 'level': 'B1'},
    {'sentence': 'Some stores will charge a set amount per pound of fruit, and will weigh customers’ fruit purchases and bill them accordingly.', 'level': 'B1'},
    {'sentence': 'Other stores will charge customers for each piece of fruit they buy, or for bundles of fruit (a bag of bananas, a bag of apples, etc.).', 'level': 'B1'},
    {'sentence': 'Other stores yet will simply charge by the container.', 'level': 'B1'},
    {'sentence': 'Vegetables, including lettuce, corn, tomatoes, onions, celery, cucumbers, mushrooms, and more are also sold at many grocery stores, and are purchased similarly to the way that fruits are.', 'level': 'B1'},
    {'sentence': 'Grocery stores typically stock more vegetables than fruit at any given time, as vegetables remain fresh longer than fruits do, generally speaking.', 'level': 'B1'},
    {'sentence': 'It’d take quite a while to list everything else that today’s massive grocery stores sell.', 'level': 'B1'},
    {'sentence': 'Most customers take the opportunity to shop for staples, or foods that play a prominent role in the average diet, at the establishments.', 'level': 'B1'},
    {'sentence': 'Staples include pasta, rice, flour, sugar, milk, meat, and eggs, and bread.', 'level': 'B1'},
    {'sentence': 'All the listed staples are available in prepackaged containers, but can be purchased "fresh" in some grocery stores, wherein employees will measure and weigh fresh products and then provide them to customers.', 'level': 'B1'},
    {'sentence': 'My job is a long distance from my home, almost 50 miles away.', 'level': 'B1'},
    {'sentence': 'I have to wake up early every morning, as I’m always in a rush.', 'level': 'B1'},
    {'sentence': 'There’s never enough time for a relaxed breakfast.', 'level': 'B1'},
    {'sentence': 'At exactly 6:00 AM, I get into my car and start the long drive.', 'level': 'B1'},
    {'sentence': 'I usually like driving on the highway more than in the city.', 'level': 'B1'},
    {'sentence': 'During the morning rush hour, though, it’s not very enjoyable.', 'level': 'B1'},
    {'sentence': 'The heavy traffic is a little bit annoying.', 'level': 'B1'},
    {'sentence': 'So I always listen to my favorite classical music CD’s in the car – Chopin, Mozart, and Bach.', 'level': 'B1'},
    {'sentence': 'That cheers me up a lot.', 'level': 'B1'},
    {'sentence': 'The drive to work takes about one hour.', 'level': 'B1'},
    {'sentence': 'Going back home in the evening after work takes even longer, maybe around 70 minutes.', 'level': 'B1'},
    {'sentence': 'Lately I’ve been thinking about trying to take the train to work instead of driving.', 'level': 'B1'},
    {'sentence': 'That way, I could still listen to my music with headphones, and even read a novel at the same time.', 'level': 'B1'},
    {'sentence': 'Halloween (also referred to as All Hollows’ Eve) is a holiday that’s celebrated in America on 31 October of each year, regardless of what day of the week this date falls on.', 'level': 'B1'},
    {'sentence': 'Although it is rooted in religion, Halloween today is enjoyed mainly because of its decorations, costumes, candy, treats, and general excitement.', 'level': 'B1'},
    {'sentence': 'Furthermore, it is enjoyed by most everyone.', 'level': 'B1'},
    {'sentence': 'Before Halloween, many individuals carve a design into an orange-colored pumpkin, or a solid, durable vegetable.', 'level': 'B1'},
    {'sentence': 'Once a personally satisfying design is carved, a lit candle is typically put inside a pumpkin, thereby making it a Jack-O-Lantern.', 'level': 'B1'},
    {'sentence': 'At night, this design lights up against the darkness.', 'level': 'B1'},
    {'sentence': 'Besides carving pumpkins, some celebrate Halloween by putting decorations up.', 'level': 'B1'},
    {'sentence': 'Supernatural (referring in this case to non-natural creatures that’re typically based in fiction) figures, including vampires, ghosts, werewolves, zombies, and more, generally account for most of these decorations.', 'level': 'B1'},
    {'sentence': 'Bugs, spiders, cobwebs, gravestones, and anything else that can be considered creepy (or unusual and possibly scary) can also be found on Halloween, in decoration form.', 'level': 'B1'},
    {'sentence': 'Only some adults celebrate Halloween, and they generally do so by attending parties.', 'level': 'B1'},
    {'sentence': 'Inversely, the vast majority of children dress in costume and walk from door to door in search of candy.', 'level': 'B1'},
    {'sentence': 'Halloween costumes can be based upon anything, from the mentioned supernatural creatures to the stars of today’s films', 'level': 'B1'},
    {'sentence': 'A practice known as trick or treat on Halloween.', 'level': 'B1'},
    {'sentence': 'After knocking on a door, one says, "Trick or Treat" and a piece of candy is given to him or her.', 'level': 'B1'},
    {'sentence': 'Houses that participate in Halloween usually leave a light on.', 'level': 'B1'},
    {'sentence': 'This is Capitol Hotels in Washington, D.C. How may I help you?', 'level': 'B1'},
    {'sentence': 'Hi, I’d like to schedule a reservation for this upcoming weekend from Friday night until Sunday.', 'level': 'B1'},
    {'sentence': 'Let me check and see what rooms are available.', 'level': 'B1'},
    {'sentence': 'Do you need a room with one bed or two?', 'level': 'B1'},
    {'sentence': 'My wife and I will be visiting the city, but a room with one bed will be just fine.', 'level': 'B1'},
    {'sentence': 'It looks like we have several rooms available.', 'level': 'B1'},
    {'sentence': 'Would you care for a room with a balcony?', 'level': 'B1'},
    {'sentence': 'A single room with no balcony will suit our needs just fine.', 'level': 'B1'},
    {'sentence': 'I did notice on your website that you have a pool and an exercise room.', 'level': 'B1'},
    {'sentence': 'Are these facilities available for all hotel guests?', 'level': 'B1'},
    {'sentence': 'Yes, all hotel guests are allowed access to those facilities.', 'level': 'B1'},
    {'sentence': 'The hotel stay also includes breakfast.', 'level': 'B1'},
    {'sentence': 'We have a restaurant on-site that also serves lunch and dinner, but those meals are not included in your lodging fee.', 'level': 'B1'},
    {'sentence': 'Okay, that’s fine.', 'level': 'B1'},
    {'sentence': 'What time are both check-in and check-out?', 'level': 'B1'},
    {'sentence': 'Check-in for you on Friday can be any time after 3:00 p.m.', 'level': 'B1'},
    {'sentence': 'Check-out will be on Sunday before noon.', 'level': 'B1'},
    {'sentence': 'Sounds great!', 'level': 'B1'},
    {'sentence': 'I am glad that I could help you today.', 'level': 'B1'},
    {'sentence': 'Is there anything else that you need at this point in time?', 'level': 'B1'},
    {'sentence': 'Would you like my credit card information now, or can I take care of that upon my arrival to the hotel’s reception desk?', 'level': 'B1'},
    {'sentence': 'We can handle payment upon your arrival on Friday.', 'level': 'B1'},
    {'sentence': 'We look forward to seeing you then!', 'level': 'B1'},
    {'sentence': 'Thank you!', 'level': 'B1'},
    {'sentence': 'I look forward to my stay', 'level': 'B1'},
    {'sentence': 'Enjoy the rest of your week!', 'level': 'B1'},
    {'sentence': 'As has been the case for many years, jobs, or forms of employment wherein employees perform a service or duty in exchange for financial compensation, play a prominent role in society.', 'level': 'B1'},
    {'sentence': 'Furthermore, all jobs—even those of seemingly little significance—are important, as they simply wouldn’t exist if their specific responsibilities weren’t of value to employers (companies or persons that pay others for their work), customers (individuals who pay money for a product or service), and the economy generally.', 'level': 'B1'},
    {'sentence': 'Teachers, or educational professionals tasked with helping students understand certain subjects and topics, are especially crucial today.', 'level': 'B1'},
    {'sentence': 'In short, teachers help their students to become qualified for their future careers.', 'level': 'B1'},
    {'sentence': 'Doctors, or medical professionals who specialize in providing health-related assistance to patients, are some of the most respected individuals in America and the world.', 'level': 'B1'},
    {'sentence': 'It’s the responsibility of doctors to help those who feel less-than-stellar to determine the underlying health issues and recommend an effective treatment (or remedy to a disease, disorder, or condition).', 'level': 'B1'},
    {'sentence': 'There are quite a few types of specialty doctors in America (besides MD, which simply means "medical doctor"), all of whom can be referred to simply as "Doctor (Name)."', 'level': 'B1'},
    {'sentence': 'Dentists (mouth/teeth doctors), dermatologists (skin doctors), and psychiatrists (mental-health doctors) are just a few examples of the many different types of doctors.', 'level': 'B1'},
    {'sentence': 'Additionally, nurses are medical professionals who help to administer doctor-ordered treatments to patients.', 'level': 'B1'},
    {'sentence': 'Police officers are law enforcement professionals whose job it is to protect citizens, solve crimes, and assure that rules and regulations are followed.', 'level': 'B1'},
    {'sentence': 'Similarly, firefighters serve the public by responding to fires (and other emergency situations) and using high-tech equipment to extinguish these fires, while bringing any individuals who’re in danger to safety.', 'level': 'B1'},
    {'sentence': 'Farmers maintain fields of crops (or vegetable/fruit plants) and/or collections of animals with the intention of selling these products as food.', 'level': 'B1'},
    {'sentence': 'Chefs/cooks prepare meals in professional settings, including restaurants, cafeterias, and other venues wherein food and drink are sold, for customers.', 'level': 'B1'},
    {'sentence': 'Chefs are generally experienced in cooking and managing kitchens.', 'level': 'B1'},
    {'sentence': 'Waiters bring menus, beverages, meals, and ultimately, the check (or a bill of the foods and drinks purchased in a transaction) to tables in restaurants and other establishments that serve food.', 'level': 'B1'},
    {'sentence': 'Artists produce art, or works of creative significance, including music, paintings, drawings, poetry, writing, and more.', 'level': 'B1'},
    {'sentence': 'London is a famous and historic city. It is the capital of England in the United Kingdom.', 'level': 'B1'},
    {'sentence': 'The city is quite popular for international tourism because London is home to one of the oldest-standing monarchies in the western hemisphere.', 'level': 'B1'},
    {'sentence': 'Rita and Joanne recently traveled to London.', 'level': 'B1'},
    {'sentence': 'They were very excited for their trip because this was their first journey overseas from the United States.', 'level': 'B1'},
    {'sentence': 'Among the popular sights that Rita and Joanne visited are Big Ben, Buckingham Palace, and the London Eye.', 'level': 'B1'},
    {'sentence': 'Big Ben is one of London’s most famous monuments.', 'level': 'B1'},
    {'sentence': 'It is a large clock tower located at the northern end of Westminster Palace.', 'level': 'B1'},
    {'sentence': 'The clock tower is 96 meters tall.', 'level': 'B1'},
    {'sentence': 'Unfortunately, Rita and Joanne were only able to view the tower from the outside.', 'level': 'B1'},
    {'sentence': 'The women learned that the tower’s interior is undergoing renovations until 2021.', 'level': 'B1'},
    {'sentence': 'Fortunately, the London Eye, the city’s famous Ferris wheel, was open to the public.', 'level': 'B1'},
    {'sentence': 'The London Eye is situated along the southern shores of the Thames River.', 'level': 'B1'},
    {'sentence': 'This attraction stands 135 meters high.', 'level': 'B1'},
    {'sentence': 'It is one of London’s most well-known spots for gaining aerial views of the city.', 'level': 'B1'},
    {'sentence': 'Each capsule of the Ferris wheel can hold up to 25 passengers.', 'level': 'B1'},
    {'sentence': 'When their capsule stopped at the top of the Ferris wheel, the women took spectacular panoramic photographs of the beautiful cityscape below.', 'level': 'B1'},
    {'sentence': 'The last place that Rita and Joanne visited was Buckingham Palace, the home of the Queen of England.', 'level': 'B1'},
    {'sentence': 'The women were impressed by the palace’s incredible architecture and historical value.', 'level': 'B1'},
    {'sentence': 'Both Rita and Joanne enjoyed watching the Queen’s guards outside the palace.', 'level': 'B1'},
    {'sentence': 'These guards wore red tunic uniforms, shiny black boots, and bearskin hats.', 'level': 'B1'},
    {'sentence': 'Despite the women’s attempts to catch the attention of the guards, the guards are specifically trained to avoid distractions.', 'level': 'B1'},
    {'sentence': 'Because of this, the guards ignored the women completely.', 'level': 'B1'},
    {'sentence': 'Joanne and Rita had an amazing time visiting the city of London, and they are inspired to seek more international travel destinations in the future.', 'level': 'B1'},
    {'sentence': 'Stephanie recently took a weekend trip to Los Angeles, California.', 'level': 'B1'},
    {'sentence': 'Los Angeles is a coastal city situated along the Pacific Ocean.', 'level': 'B1'},
    {'sentence': 'Many celebrities earned their claim to fame here.', 'level': 'B1'},
    {'sentence': 'Although the town offers many attractions centered around Hollywood culture, there is a lot to see and visit in Los Angeles.', 'level': 'B1'},
    {'sentence': 'Of course, all things related to Hollywood are popular tourist attractions.', 'level': 'B1'},
    {'sentence': 'The Hollywood Sign, located the Hollywood Hills of the Santa Monica Mountains, is a famous landmark for this star-studded town.', 'level': 'B1'},
    {'sentence': 'Once in downtown Hollywood, it’s possible to take a stroll along the Hollywood Walk of Fame.', 'level': 'B1'},
    {'sentence': 'This landmark contains more than 2500 brass stars dedicated to celebrities who have made a significant impact on the entertainment industry.', 'level': 'B1'},
    {'sentence': 'In Hollywood, visitors can even take tours of popular movie studios.', 'level': 'B1'},
    {'sentence': 'Stephanie had a chance to visit Universal Studios, which produces her favorite films.', 'level': 'B1'},
    {'sentence': 'Los Angeles is also a popular beach town, offering plenty of opportunities for sunbathing and surfing.', 'level': 'B1'},
    {'sentence': 'A common beach destination is the Santa Monica Pier, which offers rides and attractions to its visitors.', 'level': 'B1'},
    {'sentence': 'Here, Stephanie rode the iconic Ferris wheel, which offered her a spectacular view of the city and coast.', 'level': 'B1'},
    {'sentence': 'These are just some of the things Stephanie experienced during her visit to Los Angeles.', 'level': 'B1'},
    {'sentence': 'She loved her trip, and she hopes to return someday soon.', 'level': 'B1'},
    {'sentence': 'Christina visited Miami during her winter vacation.', 'level': 'B1'},
    {'sentence': 'She is from Boston, where it is cold during the winter months.', 'level': 'B1'},
    {'sentence': 'Miami, however, has a very warm climate.', 'level': 'B1'},
    {'sentence': 'There are many sunny days in Miami, and people can go to the beach all year long.', 'level': 'B1'},
    {'sentence': 'Christina spent a good portion of her trip on the beach to relax and sunbathe.', 'level': 'B1'},
    {'sentence': 'However, she also explored Miami and its surroundings.', 'level': 'B1'},
    {'sentence': 'Inspired by Miami’s proximity to the ocean, Christina visited the Miami Seaquarium to learn about marine life.', 'level': 'B1'},
    {'sentence': 'There, she watched a show using trained dolphins, killer whales, and other aquatic mammals.', 'level': 'B1'},
    {'sentence': 'She took a lot of pictures of the sea creatures jumping out of the water and performing tricks.', 'level': 'B1'},
    {'sentence': 'Christina also took an excursion to the Everglades National Park.', 'level': 'B1'},
    {'sentence': 'This park is a protected area spanning 1.5 million acres.', 'level': 'B1'},
    {'sentence': 'Because the park is mostly swampland, it is home to many reptiles.', 'level': 'B1'},
    {'sentence': 'Native animals include snakes, alligators, and crocodiles.', 'level': 'B1'},
    {'sentence': 'The park is also great for birdwatching.', 'level': 'B1'},
    {'sentence': 'Christina enjoyed hiking the trails in the Everglades and observing the wildlife in its natural environment.', 'level': 'B1'},
    {'sentence': 'When Christina returned to the city, she visited Little Havana.', 'level': 'B1'},
    {'sentence': 'This is Miami’s Cuban neighborhood.', 'level': 'B1'},
    {'sentence': 'Christina could see that Little Havana’s people demonstrated a lot of pride for their Cuban heritage.', 'level': 'B1'},
    {'sentence': 'There were many outdoor shops and vendors, live musicians, and the Cuban cuisine was delicious.', 'level': 'B1'},
    {'sentence': 'Little Havana was Christina’s favorite part about her trip to Miami.', 'level': 'B1'},
    {'sentence': 'This neighborhood made Christina feel like she had traveled to Cuba without ever having to leave the United States.', 'level': 'B1'},
    {'sentence': 'In June, Diane visited her friends who live in San Francisco, California.', 'level': 'B1'},
    {'sentence': 'This was Diane’s first time in the city, and she enjoyed her opportunities to walk around and explore.', 'level': 'B1'},
    {'sentence': 'On the first day of her trip, Diane visited the Golden Gate Bridge.', 'level': 'B1'},
    {'sentence': 'This red suspension bridge measures 1.7 miles in length.', 'level': 'B1'},
    {'sentence': 'Diane and her friends did not walk across the bridge.', 'level': 'B1'},
    {'sentence': 'However, they viewed it from the Golden Gate National Recreation Area, which offers hiking trails, picnicking areas, and presents spectacular views of the bridge and city.', 'level': 'B1'},
    {'sentence': 'Diane and her friends made sure to take a group photograph here, featuring the bridge in the background.', 'level': 'B1'},
    {'sentence': 'The next day, Diane and her friends visited Alcatraz Island.', 'level': 'B1'},
    {'sentence': 'This island is located 1.25 miles offshore in the San Francisco Bay.', 'level': 'B1'},
    {'sentence': 'It used to serve as a lighthouse, military fort, and prison.', 'level': 'B1'},
    {'sentence': 'Diane and her friends took a small tour boat across bay to reach the island.', 'level': 'B1'},
    {'sentence': 'Their visit included a guided tour through the old military base and prison. ', 'level': 'B1'},
    {'sentence': 'They also took a walk around the island to appreciate some of the native wildlife in addition to the views of the city.', 'level': 'B1'},
    {'sentence': 'Diane and her friends spent the final day of her vist in San Francisco’s downtown area.', 'level': 'B1'},
    {'sentence': 'Diane’s favorite part of her entire trip was taking a trolley to transport her up and down the hilly streets of San Francisco.', 'level': 'B1'},
    {'sentence': 'Diane did a lot of shopping downtown on her last day.', 'level': 'B1'},
    {'sentence': 'She and her friends celebrated the end of her visit by having dinner at one of San Francisco’s best restaurants.', 'level': 'B1'},
    {'sentence': 'Thanksgiving is a holiday celebrated predominantly in North America.', 'level': 'B1'},
    {'sentence': 'It possesses a different meaning in each of the countries where it’s acknowledged.', 'level': 'B1'},
    {'sentence': 'In the United States, Thanksgiving is a federal holiday, and always takes places on the Fourth Thursday in November, regardless of the date.', 'level': 'B1'},
    {'sentence': 'All government employees and most private employees are given a day off of work.', 'level': 'B1'},
    {'sentence': 'The holiday signifies the immense progress made by pilgrims, or some of the first travelers to North America, at Plymouth Plantation circa 1621.', 'level': 'B1'},
    {'sentence': 'It was at this time that the hungry and weary Pilgrims were taught (by Native Americans) how to grow and produce food on North America’s unique terrain.', 'level': 'B1'},
    {'sentence': 'Once they’d grown an abundance of food, the Pilgrims were expectedly thankful, and they celebrated alongside the Native Americans who provided them with such valuable assistance.', 'level': 'B1'},
    {'sentence': 'President Abraham Lincoln initiated the contemporary practice of Thanksgiving by calling for a "day of Thanksgiving" during one of his Civil War addresses.', 'level': 'B1'},
    {'sentence': 'In America today, Thanksgiving remains firmly engrained in its historical roots, and is widely considered to be a day for giving thanks for good food, good times, and family.', 'level': 'B1'},
    {'sentence': 'Thanksgiving dinner generally consists of turkey, mashed potatoes, stuffing, vegetables, gravy, and ample desserts.', 'level': 'B1'},
    {'sentence': 'To be sure, indulging in abundance is a cornerstone of the holiday, as doing so could only be possible if one possesses abundance.', 'level': 'B1'},
    {'sentence': 'When exploring New York City, there are several different options for activities during a day trip.', 'level': 'B1'},
    {'sentence': 'Some visitors come to see a show, visit art museums, or simply to shop in many of the city’s high-end retailers.', 'level': 'B1'},
    {'sentence': 'However, many tourists simply come to New York City for the sightseeing.', 'level': 'B1'},
    {'sentence': 'One of the most visited landmarks in New York City is the Empire State Building.', 'level': 'B1'},
    {'sentence': 'The Empire State Building, constructed in 1931, is a 102-story skyscraper, the ninth highest building in the world, and the fourth tallest structure in the United States.', 'level': 'B1'},
    {'sentence': 'It is located in Midtown, Manhattan.', 'level': 'B1'},
    {'sentence': 'This skyscraper is an iconic symbol of the city, having been featured in over 90 popular movies (as of 2018) throughout film history.', 'level': 'B1'},
    {'sentence': 'Tourists come from all over the world to visit this building and view the city from its famous observation decks.', 'level': 'B1'},
    {'sentence': 'Matthew, an enthusiast of historic buildings, was excited for this trip to New York City because he has always appreciated architectural design.', 'level': 'B1'},
    {'sentence': 'Matthew purchased a ticket that granted him access to beautiful 360-degree views of the city.', 'level': 'B1'},
    {'sentence': 'The ticket included an elevator ride that stopped at two different vantage points, one at the 86th floor and the other at the rooftop observatory on the 102nd floor.', 'level': 'B1'},
    {'sentence': 'From these observation decks, Matthew took incredible photographs of the entire New York City skyline.', 'level': 'B1'},
    {'sentence': 'The rooftop views granted Matthew perfect aerial perspectives of Central Park, the Brooklyn Bridge, Times Square, the Statue of Liberty, and many other important city landmarks.', 'level': 'B1'},
    {'sentence': 'The four seasons are spring, summer, fall, and winter.', 'level': 'B1'},
    {'sentence': 'Although various areas of the United States experience drastically different weather during these times, all portions of the country recognize the seasons.', 'level': 'B1'},
    {'sentence': 'Winter in California may bring heat, and winter in New York may bring blizzards, but both periods are nevertheless winter.', 'level': 'B1'},
    {'sentence': 'Following winter, spring begins on 20 March and ends on either 20 June or 21 June, in the United States.', 'level': 'B1'},
    {'sentence': 'This date may vary slightly from year to year and hemisphere to hemisphere', 'level': 'B1'},
    {'sentence': 'For most, spring is a time of "thawing," when the cold and snow of the winter are replaced by sunshine, reasonable temperatures, green grass, and more.', 'level': 'B1'},
    {'sentence': 'It is also the season wherein previously dormant bees and butterflies reemerge, and when birds become more active.', 'level': 'B1'},
    {'sentence': 'Summer follows spring and spans from about 21 June to 22 September, in America.', 'level': 'B1'},
    {'sentence': 'Summer is the warmest, the longest, and (arguably) the liveliest of the four seasons.', 'level': 'B1'},
    {'sentence': 'Students from kindergarten to college are given two or so summer months off from class, and to be sure, there are more young individuals out and about during this season than any other.', 'level': 'B1'},
    {'sentence': 'It’s not uncommon to see shorts, t-shirts, and sunglasses worn by those who’re soaking up the summer’s hot sun.', 'level': 'B1'},
    {'sentence': 'To stay cool, many individuals crank the air conditioning, take a dip in a swimming pool, and/or explore the ever-comforting ocean waves.', 'level': 'B1'},
    {'sentence': 'Autumn (or fall), more than being a simple precursor to winter, is one of the most beautiful and exciting seasons.', 'level': 'B1'},
    {'sentence': 'Spanning from 22 September to 21 December in the US, autumn is characterized by falling leaves, Halloween (on 31 October), and Thanksgiving.', 'level': 'B1'},
    {'sentence': 'Technically, that is; snow will begin to fall long before this latter date, in most parts of the country, leading many to classify the period as winter.', 'level': 'B1'},
    {'sentence': 'During fall, traditional farmers harvest their produce, and the aforementioned falling leaves change to gorgeous orange, red, and yellow colors.', 'level': 'B1'},
    {'sentence': 'These colors are generally associated with autumn itself, in turn.', 'level': 'B1'},
    {'sentence': 'In the US, winter spans from 21 December to 20 March, and is, as one would expect, the coldest of the four seasons.', 'level': 'B1'},
    {'sentence': 'In the eastern, northern, and central portions of the country, winter snowfall can be considerable.', 'level': 'B1'},
    {'sentence': 'In the western and southern portions of the country, winter snowfall is highly unlikely, but temperatures nevertheless drop from their usual.', 'level': 'B1'},
    {'sentence': 'Winter is most widely known for its snow and the Christmas holiday, but it also boasts New Year’s Eve (on December 31, in recognition of the start of a new year) and other special days.', 'level': 'B1'},
    {'sentence': 'Ice skating, sledding, ice hockey, and snowball fights are commonly enjoyed winter activities.', 'level': 'B1'},
    {'sentence': 'Some of the most important landmarks in the United States include feats of architecture and modern engineering.', 'level': 'B1'},
    {'sentence': 'San Francisco, California, is a beautiful city on its own, but it is also home to The Golden Gate Bridge, a 1.7 mile suspension bridge connecting the San Francisco Peninsula to the Marin Headlands.', 'level': 'B1'},
    {'sentence': 'The bridge holds the title of one of the Wonders of the Modern World according to the American Society of Civil Engineers.', 'level': 'B1'},
    {'sentence': 'One of the most popular ways to appreciate the bridge is to take an excursion to the Golden Gate National Recreation Area just outside of San Francisco.', 'level': 'B1'},
    {'sentence': 'The park contains hiking trails, great spots for picnicking, and offers some of the best vantage points for panoramic photographs of the bridge leading into the city.', 'level': 'B1'},
    {'sentence': 'David recently had some friends visit him in San Francisco, and he made sure to include a visit to the recreation area as part of their tour.', 'level': 'B1'},
    {'sentence': 'They enjoyed walking through the trails, observing some of the native wildlife, and even having a casual picnic in the park.', 'level': 'B1'},
    {'sentence': 'David’s friends were thankful that he guided them through this impressive area of California.', 'level': 'B1'},
    {'sentence': 'They made sure to take a group photograph with the Golden Gate Bridge in the background.', 'level': 'B1'},
    {'sentence': 'David’s friends had the picture framed, and they later presented it to David in order to thank him for his hospitality during their stay.', 'level': 'B1'},
    {'sentence': 'The Grand Canyon, one of the Seven Wonders of the Natural World, is located in the state of Arizona.', 'level': 'B1'},
    {'sentence': 'It is also a UNESCO World Heritage Site. Formed by over 70 million years of erosion from the Colorado River, the Grand Canyon offers a spectacular view.', 'level': 'B1'},
    {'sentence': 'The canyon spans 277 miles in length, up to 18 miles in width, and it measures over a mile in depth at its deepest points.', 'level': 'B1'},
    {'sentence': 'Carlos always wanted to visit the Grand Canyon, and recently he received the chance to hike some of the trails and take several panoramic photographs during his visit.', 'level': 'B1'},
    {'sentence': 'When Carlos arrived at the visitor center, he watched a brief movie that taught tourists about the Grand Canyon National Park and the geological history of the canyon’s formation.', 'level': 'B1'},
    {'sentence': 'Later, Carlos followed a hiking trail to become even further acquainted with the canyon.', 'level': 'B1'},
    {'sentence': 'While walking through the trails, Carlos saw some tourists riding donkeys to traverse the canyon’s ridges.', 'level': 'B1'},
    {'sentence': 'Throughout his hiking expedition, Carlos used a map to find some of the best hot spots for photographs within the canyon.', 'level': 'B1'},
    {'sentence': 'He revisited some areas at different points in the day because sun angles and lighting can make a big difference in the quality of a photo.', 'level': 'B1'},
    {'sentence': 'Carlos was very pleased that he got to travel to the Grand Canyon.', 'level': 'B1'},
    {'sentence': 'He loves hiking and photography, so this was the perfect outdoor experience for him.', 'level': 'B1'},
    {'sentence': 'He posted all of his best pictures on social media, and his friends were amazed by his breathtaking, panoramic shots.', 'level': 'B1'},
    {'sentence': 'The Statue of Liberty, arguably one of New York City’s most iconic symbols, is a popular tourist attraction for first-time visitors to the city.', 'level': 'B1'},
    {'sentence': 'This 150-foot monument was gifted to the United States from France in order to celebrate 100 years of America’s independence.', 'level': 'B1'},
    {'sentence': 'The statue is located on Liberty Island, and it is accessible by taking a ferry from either Battery Park in New York City or Liberty State Park in Jersey City.', 'level': 'B1'},
    {'sentence': 'When Claire visited the Statue of Liberty for the first time, she instantly admired it as a symbol of freedom.', 'level': 'B1'},
    {'sentence': 'Claire made sure to make reservations before her visit because only 240 people are permitted to climb the staircase to the top of the statue every day.', 'level': 'B1'},
    {'sentence': 'After climbing almost 400 stairs, Claire received spectacular views of the city from the statue’s crown.', 'level': 'B1'},
    {'sentence': 'During her visit, Claire learned that the Statue of Liberty was not always the color that it is now.', 'level': 'B1'},
    {'sentence': 'She found out that because the statue’s exterior is made of copper, the statue oxidized over time, giving it the greenish appearance it has in present day.', 'level': 'B1'},
    {'sentence': 'When it was first constructed, the statue was the same color as a shiny penny!', 'level': 'B1'},
    {'sentence': 'After touring the Statue of Liberty, Claire spent the rest of the day in New York City visiting other important monuments and historic landmarks.', 'level': 'B1'},
    {'sentence': 'Claire left New York hoping to have had the time to explore more sites, but she can’t wait to return to the city in the future.', 'level': 'B1'},
    {'sentence': 'Valentine’s Day (or Saint Valentine’s Day) is a holiday that, in the United States, takes place on February 14, and technically signifies the accomplishments of St. Valentine, a third-century Roman saint.', 'level': 'B1'},
    {'sentence': 'With that said, most Americans, instead of honoring St. Valentine through religious ceremony, enjoy the holiday by engaging in "romantic" behavior with their significant other or someone who they wish to be their significant other.', 'level': 'B1'},
    {'sentence': 'Gifts, special dinners, and other acknowledgements of affection comprise most individuals’ Valentine’s Day celebrations.', 'level': 'B1'},
    {'sentence': 'Chocolates and flowers are commonly given as gifts during Valentine’s Day, as are accompanying greeting cards (greeting card companies release new Valentine’s Day designs annually).', 'level': 'B1'},
    {'sentence': 'Red and pink are generally understood to be "the colors" of Valentine’s Day, and many individuals, instead of celebrating romantically, spend the holiday with their friends and/or family members.', 'level': 'B1'},
    {'sentence': 'Variations of Valentine’s Day are celebrated across the globe throughout the year.', 'level': 'B1'},
    {'sentence': 'In America, the holiday, although acknowledged by the vast majority of the population, isn’t federally recognized; no time off work is granted for Valentine’s Day.', 'level': 'B1'},
    {'sentence': 'Yesterday, Stephen returned from a trip to Washington, D.C., the capital of the United States.', 'level': 'B1'},
    {'sentence': 'His visit took place during the week prior to the Fourth of July.', 'level': 'B1'},
    {'sentence': 'Logically, there were many activities and celebrations in town in preparation for Independence Day.', 'level': 'B1'},
    {'sentence': 'During his stay in the city, Stephen visited a lot of important historical sites and monuments, and he left with a deeper understanding of the political history of the United States.', 'level': 'B1'},
    {'sentence': 'Stephen spent a lot of time outdoors exploring the important monuments surrounding Capitol Hill.', 'level': 'B1'},
    {'sentence': 'Of course, he saw the White House from its outside gate at 1600 Pennsylvania Avenue.', 'level': 'B1'},
    {'sentence': 'Stephen also visited the Washington Monument, the Jefferson Memorial, and the Lincoln Memorial.', 'level': 'B1'},
    {'sentence': 'These statues and pavilions are dedicated to former U.S. presidents.', 'level': 'B1'},
    {'sentence': 'They commemorate the contributions that these leaders made throughout American history.', 'level': 'B1'},
    {'sentence': 'Washington, D.C. also has several war memorials dedicated to fallen soldiers during the major wars of the 20th century.', 'level': 'B1'},
    {'sentence': 'Away from the Capitol Hill area, Washington, D.C. has many museums and art galleries worth visiting.', 'level': 'B1'},
    {'sentence': 'Stephen enjoyed his visit to Washington, D.C. because he learned a lot more about American history after touring each important landmark.', 'level': 'B1'},
    {'sentence': 'Yellowstone National Park, located in Idaho, Montana, and Wyoming, was established as the first national park in the United States.', 'level': 'B1'},
    {'sentence': 'The park is a popular destination for visitors who enjoy ecological tourism as it offers forests, mountains, and abundant ecosystems to explore.', 'level': 'B1'},
    {'sentence': 'Some of Yellowstone’s most well-known landmarks are its geothermal hot springs and geysers, the most famous of which is named Old Faithful.', 'level': 'B1'},
    {'sentence': 'Last fall, Lisa and her friends decided to take a camping trip to Yellowstone National Park.', 'level': 'B1'},
    {'sentence': 'They arranged to stay at one of the park’s many convenient campsites.', 'level': 'B1'},
    {'sentence': 'For their camping trip, they brought their backpacks, sleeping bags, and a cooler of food and drinks.', 'level': 'B1'},
    {'sentence': 'They pitched their tents immediately upon arriving to their campsite.', 'level': 'B1'},
    {'sentence': 'During their trip, Lisa and her friends hiked the many trails of the park, exploring its natural surroundings.', 'level': 'B1'},
    {'sentence': 'In the forest, they saw a lot of local wildlife.', 'level': 'B1'},
    {'sentence': 'Lisa was surprised to see a family of grizzly bears, some gray wolves, and even bald eagles flying overhead.', 'level': 'B1'},
    {'sentence': 'Outside of the woods, they admired the beauty of some of Yellowstone’s natural cascades.', 'level': 'B1'},
    {'sentence': 'Since Yellowstone contains many hot springs and the world’s largest area of active geysers, Lisa and her friends visited many different geyser sites.', 'level': 'B1'},
    {'sentence': 'They even spent an afternoon swimming in Yellowstone’s Boiling River.', 'level': 'B1'},
    {'sentence': 'Of all of the sites, Lisa and her friends agreed that Old Faithful was the most impressive.', 'level': 'B1'},
    {'sentence': 'Lisa and her friends waited patiently for the geyser to erupt.', 'level': 'B1'},
    {'sentence': 'After about 40 minutes, a stream of boiling water over 100 feet tall sprayed from the ground and up into the air.', 'level': 'B1'},
    {'sentence': 'Fortunately, no one got wet!', 'level': 'B1'},
    {'sentence': 'It goes without saying that humans (mammals identifiable as those that stand upright and are comparatively advanced and capable of detailed thought) have pretty remarkable bodies, given all that they’ve accomplished.', 'level': 'B2'},
    {'sentence': 'Furthermore, an especially intelligent human brain produced this text!', 'level': 'B2'},
    {'sentence': 'To be sure, humans have overcome predators, disease, and all sorts of other obstacles over thousands of years.', 'level': 'B2'},
    {'sentence': 'To fully understand and appreciate these accomplishments, let’s take at some of the most well-known parts of the human body!', 'level': 'B2'},
    {'sentence': 'The head, or the spherical body part that contains the brain and rests at the top of the human body, has quite a few individual organs and body parts on it.', 'level': 'B2'},
    {'sentence': 'It should quickly be mentioned that hair occupies the space on top of the head, and the ears, the organs responsible for hearing, are located on either side of the head.', 'level': 'B2'},
    {'sentence': 'From top to bottom, the eyebrows, or horizontal strips of hair that can be found above the eye, are the first components of the head.', 'level': 'B2'},
    {'sentence': 'The eyes are below them, and are round, orb-like organs that allow humans to see.', 'level': 'B2'},
    {'sentence': 'The eyes make way for the nose, or an external (sticking-out) organ that plays an important part in the breathing and bacteria-elimination processes.', 'level': 'B2'},
    {'sentence': 'Below that is the mouth, or a wide, cavernous organ that chews food, removes bacteria, helps with breathing, and more.', 'level': 'B2'},
    {'sentence': 'The mouth contains teeth, or small, white-colored, pointed body parts used to chew food, and the tongue, or a red-colored, boneless organ used to chew food and speak.', 'level': 'B2'},
    {'sentence': 'The neck is the long body part that connects the head to the chest (the muscular body part that protects the heart and lungs), and the stomach, or the part of the body that contains food and liquid-processing organs, comes below that.', 'level': 'B2'},
    {'sentence': 'The legs are the long, muscular body parts that allow humans to move from one spot to another and perform a variety of actions.', 'level': 'B2'},
    {'sentence': 'Each leg contains a thigh (a thick, especially muscular body part used to perform strenuous motions; the upper part of the leg) and a calf (thinner, more flexible body part that absorbs the shock associated with movement; the lower part of the leg).', 'level': 'B2'},
    {'sentence': 'Feet can be found at the bottom of legs, and each foot is comprised of five toes, or small appendages that help balance.', 'level': 'B2'},
    {'sentence': 'Arms are long, powerful body parts that are located on either side of chest, below the shoulders.', 'level': 'B2'},
    {'sentence': 'Arms are comprised of biceps (the thicker, more powerful upper portion), and forearms (the thinner, more flexible lower portion)', 'level': 'B2'},
    {'sentence': 'Hands, or small, gripping body parts used for a tremendous number of actions, are at the end of arms.', 'level': 'B2'},
    {'sentence': 'Each hand contains five fingers, or small appendages used to grip objects.', 'level': 'B2'},
    {'sentence': 'The aforementioned shoulders are rounded body parts that aid arms’ flexibility. ', 'level': 'B2'},
    {'sentence': 'One’s back is found on the opposite side of the stomach, and is a flat section of the body that contains important muscles that’re intended to protect the lungs and other internal organs, in addition to helping humans perform certain motions and actions.', 'level': 'B2'},
    {'sentence': 'Last April, John took a trip to Las Vegas, Nevada.', 'level': 'B2'},
    {'sentence': 'Las Vegas is a popular destination in the western portion of the United States.', 'level': 'B2'},
    {'sentence': 'The town is most popular for its casinos, hotels, and exciting nightlife.', 'level': 'B2'},
    {'sentence': 'In downtown Las Vegas, John spent a lot of time on The Strip, which is a 2.5 mile stretch of shopping, entertainment venues, luxury hotels, and fine dining experiences.', 'level': 'B2'},
    {'sentence': 'This is probably the most commonly visited tourist area in the city. ', 'level': 'B2'},
    {'sentence': 'The Strip at night looks especially beautiful. All of the buildings light up with bright, neon, eye-catching signs to attract visitor attention.', 'level': 'B2'},
    {'sentence': 'A stay in Las Vegas can feel similar to a visit to many popular cities worldwide.', 'level': 'B2'},
    {'sentence': 'Many of the hotels have miniature versions of important international sites and monuments.', 'level': 'B2'},
    {'sentence': 'These famous landmarks include the Eiffel Tower, Venice, and even ancient Rome.', 'level': 'B2'},
    {'sentence': 'One day, John took a side trip outside of the city to visit the Grand Canyon, one of the Seven Wonders of the Natural World.', 'level': 'B2'},
    {'sentence': 'The canyon offers a breathtaking view of Nevada’s ridges and natural landscape.', 'level': 'B2'},
    {'sentence': 'John especially liked the canyon because it was removed from all of the noise and movement in downtown Las Vegas.', 'level': 'B2'},
    {'sentence': 'John had a great time during his trip to Las Vegas.', 'level': 'B2'},
    {'sentence': 'He did not win a lot of money in the casinos.', 'level': 'B2'},
    {'sentence': 'However, he managed to see a lot of amazing sites during his visit to this city that never sleeps.', 'level': 'B2'},
    {'sentence': 'The deadliest virus in modern history, perhaps of all time, was the 1918 Spanish Flu.', 'level': 'C1'},
    {'sentence': 'It killed about 20 to 50 million people worldwide, perhaps more.', 'level': 'C1'},
    {'sentence': 'The total death toll is unknown because medical records were not kept in many areas.', 'level': 'C1'},
    {'sentence': 'The pandemic hit during World War I and devastated military troops.', 'level': 'C1'},
    {'sentence': 'In the United States, for instance, more servicemen were killed from the flu than from the war itself.', 'level': 'C1'},
    {'sentence': 'The Spanish flu was fatal to a higher proportion of young adults than most flu viruses.', 'level': 'C1'},
    {'sentence': 'The pandemic started mildly, in the spring of 1918, but was followed by a much more severe wave in the fall of 1918.', 'level': 'C1'},
    {'sentence': 'The war likely contributed to the devastating mortality numbers, as large outbreaks occurred in military forces living in close quarters.', 'level': 'C1'},
    {'sentence': 'Poor nutrition and the unsanitary conditions of war camps had an effect.', 'level': 'C1'},
    {'sentence': 'A third wave occurred in the winter and spring of 1919, and a fourth, smaller wave occurred in a few areas in spring 1920.', 'level': 'C1'},
    {'sentence': 'Initial symptoms of the flu were typical: sore throat, headache, and fever.', 'level': 'C1'},
    {'sentence': 'The flu often progressed rapidly to cause severe pneumonia and sometimes hemorrhage in the lungs and mucus membranes.', 'level': 'C1'},
    {'sentence': 'A characteristic feature of severe cases of the Spanish Flu was heliotrope cyanosis, where the patient’s face turned blue from lack of oxygen in the cells.', 'level': 'C1'},
    {'sentence': 'Death usually followed within hours or days.', 'level': 'C1'},
    {'sentence': 'Modern medicine such as vaccines, antivirals, and antibiotics for secondary infections were not available at that time, so medical personnel couldn’t do much more than try to relieve symptoms.', 'level': 'C1'},
    {'sentence': 'The flu ended when it had infected enough people that those who were susceptible had either died or developed immunity.', 'level': 'C1'},
    {'sentence': 'In our modern world, there are many factors that place the wellbeing of the planet in jeopardy.', 'level': 'C1'},
    {'sentence': 'While some people have the opinion that environmental problems are just a natural occurrence, others believe that human beings have a huge impact on the environment.', 'level': 'C1'},
    {'sentence': 'Regardless of your viewpoint, take into consideration the following factors that place our environment as well as the planet Earth in danger.', 'level': 'C1'},
    {'sentence': 'Global warming or climate change is a major contributing factor to environmental damage.', 'level': 'C1'},
    {'sentence': 'Because of global warming, we have seen an increase in melting ice caps, a rise in sea levels, and the formation of new weather patterns.', 'level': 'C1'},
    {'sentence': 'These weather patterns have caused stronger storms, droughts, and flooding in places that they formerly did not occur.', 'level': 'C1'},
    {'sentence': 'Air pollution is primarily caused as a result of excessive and unregulated emissions of carbon dioxide into the air.', 'level': 'C1'},
    {'sentence': 'Pollutants mostly emerge from the burning of fossil fuels in addition to chemicals, toxic substances, and improper waste disposal.', 'level': 'C1'},
    {'sentence': 'Air pollutants are absorbed into the atmosphere, and they can cause smog, a combination of smoke and fog, in valleys as well as produce acidic precipitation in areas far away from the pollution source.', 'level': 'C1'},
    {'sentence': 'In many areas, people and local governments do not sustainably use their natural resources.', 'level': 'C1'},
    {'sentence': 'Mining for natural gases, deforestation, and even improper use of water resources can have tremendous effects on the environment.', 'level': 'C1'},
    {'sentence': 'While these strategies often attempt to boost local economies, their effects can lead to oil spills, interrupted animal habitats, and droughts.', 'level': 'C1'},
    {'sentence': 'Ultimately, the effects of the modern world on the environment can lead to many problems.', 'level': 'C1'},
    {'sentence': 'Human beings need to consider the repercussions of their actions, trying to reduce, reuse, and recycle materials while establishing environmentally sustainable habits.', 'level': 'C1'},
    {'sentence': 'If measures are not taken to protect the environment, we can potentially witness the extinction of more endangered species, worldwide pollution, and a completely uninhabitable planet.', 'level': 'C1'},
]



